### ISSUE TITLE
proteore.org: GoProfiles "Fatal error"

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#261]
with the following errr msg...
Fatal error: Exit code 1 ()
Error in library(goProfiles, quietly = TRUE) : 
  there is no package called ‘goProfiles’
Calls: suppressMessages -> withCallingHandlers -> library
Execution halted
History "uPE1_Male Tissue_20191210" shared with All of you
item n°26

**Comment by davidchristiany** [comment]
there is an error in the requirements:
<requirement type="package" version="3.8.2">-org.hs.eg.db</requirement>
instead of 
<requirement type="package" version="3.8.2">bioconductor-org.hs.eg.db</requirement>

I corrected the xml file, I will put the corrected version on the toolshed and reinstall it.

**Comment by yvandenb** [comment]
Many thx David !

**Comment by davidchristiany** [comment]
Done, you can test it

**Comment by yvandenb** [comment]
Works fine ! :-)

**Comment by combesf** [comment]
Is it "normal" this error occurs only for this tool, and not for all the other tools that require "org.hs.eg.db" package ?

**Comment by davidchristiany** [comment]
Yes it was because of an error in the requirements
